spring:
  application:
    name: nemi-product-manager
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://nemi-uat.cbwe2q8wsga5.ap-southeast-1.rds.amazonaws.com:5432/dev_nemi
    username: dev_nemi_product_manager
    password: Nemi123#
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 120000
      validation-timeout: 5000
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_batch_size: 200
          order_inserts: true
          order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        format_sql: true

server:
  port: 5201
  error:
    include-stacktrace: never

async:
  sync:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 200
  batch:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 500

nhanhvn:
  base-url: https://nhanh.vn
  pos-url: https://pos.open.nhanh.vn
  return-link: https://nemi-dev-02.ecombase.net/nemi-product-manager/nhanhvn/auth
  api-version: v3.0
  url-oauth: oauth
  url-access-token: app/getaccesstoken
  url-products: product/list
  url-orders: order/list
  recent-days: 30 # số ngày gần nhất để lấy sản phẩm
  product:
    status:
      mapping:
        1: "new"          # Mới - bán tại cửa hàng offline
        2: "selling"      # Đang bán - hiển thị trên website & cửa hàng offline
        3: "stopped"      # Ngừng bán - ẩn khỏi website và cửa hàng
        4: "out_of_stock" # Hết hàng - hiển thị trên website nhưng không cho đặt hàng
  order:
    status:
      mapping:
        54: "NEW"           # Đơn mới
        55: "PROCESSING"    # Đang xác nhận
        56: "PROCESSING"    # Đã xác nhận
        57: "PROCESSING"    # Chờ khách xác nhận
        42: "PROCESSING"    # Đang đóng gói
        40: "PROCESSING"    # Đã đóng gói
        43: "READY_TO_SHIP" # Chờ thu gom
        59: "SHIPPING"      # Đang chuyển
        60: "DELIVERED"     # Thành công
        58: "CANCELLED"     # Hãng vận chuyển hủy
        63: "CANCELLED"     # Khách hủy
        64: "CANCELLED"     # Hệ thống hủy
        68: "CANCELLED"     # Hết hàng
        61: "FAILED"        # Thất bại
        71: "RETURNED"      # Đang chuyển hoàn
        72: "RETURNED"      # Đã chuyển hoàn
        73: "RETURNED"      # Đổi kho xuất hàng
        74: "RETURNED"      # Xác nhận hoàn
  sync:
    batch-size: 100
    page-size: 100
pancake:
  base-url: https://pos.pages.fm/api/v1
  is-sync-all-product: false
  is-sync-all-order: false
  recent-days: 30
  shop-id: 1720119150
  timeout: 30000
  order:
    status:
      mapping:
        0: "NEW"            # Mới
        20: "NEW"            # Đã đặt hàng
        1: "PROCESSING"     # Đã xác nhận
        11: "PROCESSING"     # Chờ hàng
        12: "PROCESSING"     # Chờ in
        13: "PROCESSING"     # Đã in
        8: "PROCESSING"     # Đang đóng hàng
        9: "READY_TO_SHIP"  # Chờ chuyển hàng
        2: "SHIPPING"       # Đã gửi hàng
        3: "DELIVERED"      # Đã nhận
        16: "DELIVERED"      # Đã thu tiền
        4: "RETURNED"       # Đang hoàn
        15: "RETURNED"       # Hoàn một phần (partial return – note riêng nếu cần)
        5: "RETURNED" # Đã hoàn
        6: "CANCELLED"      # Đã hủy
        7: "CANCELLED"      # da xoa
  sync:
    order: 1000
    order-item: 200
    product: 100
    page-start: 1

sapo:
  url: https://nemi-test02.mysapo.net/
  recent-days: 30 # số ngày gần nhất để lấy sản phẩm
  is-sync-all-product: false
  is-sync-all-order: false
  url-register-webhook: https://nemi-dev-02.ecombase.net/nemi-product-manager/webhook/v1/sapo/
  # API Paths
  path-oauth-access-token: /admin/oauth/access_token
  path-products: /admin/products.json
  path-webhooks: /admin/webhooks.json
  webhook:
    topic:
      - orders/create
      - orders/delete
      - orders/updated
#      - orders/paid                # Khi đơn hàng được thanh toán thành công
#      - orders/cancelled           # Khi đơn hàng bị hủy
#      - orders/fulfilled           # Khi đơn hàng đã được giao
#      - orders/partially_fulfilled # Khi đơn hàng được giao một phần

      # Product events
      - products/create
      - products/update
      - products/delete

  order:
    status:
      mapping:
        open: "processing"     # Tất cả các order đang hoạt động
        closed: "delivered"    # Các order đã lưu trữ
        cancelled: "cancelled" # Các order bị hủy
  sync:
    page-start: 1
    product-limit: 250
    batch-size: 100

secret:
  jwt-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArh1qU7sGe0uiquAuZo9+T4RTLZoG5NdtHtPCxcFp04EaTJFF+EmN/hwC0v3BXjNbvHYOPfUkmZ98QGeGXE6Q8xp3RGJafrmg6IAOzcWVSaVS4X0hlZjUNs5gW197ojhCCPRuWUSdSmAJG1i+CLQPn+pCBK7Wy2sJ6JTVtnuvs6LaUeqL9B7yE4LaMgEJo9ubi/TCrkD6dI4mxrqsVQVDpaHxau+sZbBsbGD/V4rWfFv7XqAbqWbam3gF/Qr2q/321sLkYjoSEG5sLxaDLgrDPk2moZ1PyLtuDpeF1DWygcK7XRsZjD3j4LkV2K4Ubi+P2wQCI+oZfM1XVlslzKKnVQIDAQAB"
  service-username: "nemi"
  service-password: "Nemi@2025@"

crypto:
  password: "Nemi@2025@!"
  mode: GCM         # GCM or CTR
  strength: 256     # 128, 192, 256
logging:
  level:
    root: info
    com:
      nemi: debug
    org.apache: off
  file:
    name: /tmp/log/nemi.log
  logback:
    rollingpolicy:
      file-name-pattern: /tmp/log/nemi.%d{yyyy-MM-dd}.%i.log
      max-history: 30
      max-file-size: 10MB
      total-size-cap: 1GB
      clean-history-on-start: false



webhook:
  base-url: https://nemi-dev-02.ecombase.net/nemi-product-manager/webhook
  version: v1
  allowed-ips:
    nhanhvn:
      - 34.80.130.93
      - 104.199.211.99
      - 35.185.145.223
    pancake:
      - 203.171.22.6
    sapo:
      - 42.113.206.190
  rate-limit:
    enable: true
    partners:
      nhanhvn:
        limit: 60
        window-size: 60000
        segment-size: 1000
      pancake:
        limit: 60
        window-size: 60000
        segment-size: 1000
      sapo:
        limit: 60
        window-size: 60000
        segment-size: 1000

nemi:
  feign:
    user-manager:
      base-url: http://localhost:5200
