spring:
  application:
    name: nemi-product-manager
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://nemi-uat.cbwe2q8wsga5.ap-southeast-1.rds.amazonaws.com:5432/dev_nemi
    username: dev_nemi_product_manager
    password: Nemi123#
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        format_sql: true

server:
  port: 5200
  error:
    include-stacktrace: never

nhanhvn:
  base-url: https://pos.open.nhanh.vn
  api-version: v3.0
  url-access-token: app/getaccesstoken
  url-products: product/list
  url-orders: /order/list
  verify-token: nemiWebhook123!@#
  secret-key: NHdyJR8NKO2v8Md7Nwb06o1n0nOAW5YcLBeQs4DdyoLmoXJK8jz6Hf3nQcadBx2m5Ys9kGydcKs0g3Kn94rVgXyU1nhmDtQSZipWJjiHo5A6ffCamfsL81DXUSm9n3AT
  order:
    status:
      mapping:
        54: "new"           # Đơn mới
        55: "processing"    # Đang xác nhận
        56: "processing"    # Đã xác nhận
        57: "processing"    # Chờ khách xác nhận
        42: "processing"    # Đang đóng gói
        40: "processing"    # Đã đóng gói
        43: "ready_to_ship" # Chờ thu gom
        59: "shipping"      # Đang chuyển
        60: "delivered"     # Thành công
        58: "cancelled"     # Hãng vận chuyển hủy
        63: "cancelled"     # Khách hủy
        64: "cancelled"     # Hệ thống hủy
        68: "cancelled"     # Hết hàng
        61: "failed"        # Thất bại
        71: "returned"      # Đang chuyển hoàn
        72: "returned"      # Đã chuyển hoàn
        73: "returned"      # Đổi kho xuất hàng
        74: "returned"      # Xác nhận hoàn

pancake:
  secret: elqsF9ERiFWGacWQO9Gg5XC4kXojot
  base-url: https://pos.pages.fm/api/v1
  api-key: 10b76cf31be245848c8361287cee2adf
  shop-id: 1720119150
  timeout: 30000
  retry:
    max-attempts: 3
    backoff-delay: 2000
  sync:
    page-size: 50 # So luong ban ghi lay ve trong 1 lan
    batch-size: 100 # So luong ban ghi xu ly trong 1 lan
    max-concurrent: 1 # So request dong thoi
sapo:
  client-id: 50f184d93c834ebaa764cc17c25e31fa
  client-secret: 50ce6b4d47a04ca18aa6f972b698779a
  access-token: 59d0c4eea0fc497e81733f693d3e4641
  url: https://nemi-test.mysapo.net/

secret:
  jwt-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArh1qU7sGe0uiquAuZo9+T4RTLZoG5NdtHtPCxcFp04EaTJFF+EmN/hwC0v3BXjNbvHYOPfUkmZ98QGeGXE6Q8xp3RGJafrmg6IAOzcWVSaVS4X0hlZjUNs5gW197ojhCCPRuWUSdSmAJG1i+CLQPn+pCBK7Wy2sJ6JTVtnuvs6LaUeqL9B7yE4LaMgEJo9ubi/TCrkD6dI4mxrqsVQVDpaHxau+sZbBsbGD/V4rWfFv7XqAbqWbam3gF/Qr2q/321sLkYjoSEG5sLxaDLgrDPk2moZ1PyLtuDpeF1DWygcK7XRsZjD3j4LkV2K4Ubi+P2wQCI+oZfM1XVlslzKKnVQIDAQAB"
  service-username: "nemi"
  service-password: "Nemi@2025@"
logging:
  level:
    root: info
    com:
      nemi: debug
    org.apache: off
  file:
    name: /tmp/log/nemi.log
  logback:
    rollingpolicy:
      file-name-pattern: /tmp/log/nemi.%d{yyyy-MM-dd}.%i.log
      max-history: 30
      max-file-size: 10MB
      total-size-cap: 1GB
      clean-history-on-start: false






